apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: virtual-git-plugin
      generate:
        command: ["python3"]
        args: ["/home/argocd/cmp-server/plugins/virtual-git-plugin.py"]
